#how many lines can a player have,
maxBarSize: 3

#enable condition matches or not
#Please notice that if a player who is in a condition changed the skills in bar, the changes will not save to disk
enableCondition: false