name: SecondSkillBar
main: com.github.MrMks.skillbar.bukkit.SkillBar
version: ${version}
depend:
  - SkillAPI
permissions:
  skillbar.ban:
    default: op
    description: permission to bar / unban a player in skillbar
  skillbar.version:
    default: op
    description: permission to see the version of plugin
  skillbar.reload:
    default: op
    description: permission to reload bar plugin
  skillbar.forceban:
    default: false
    description: permission to add / remove a player in black list without any check
  skillbar.info:
    default: true
    description: permission to see info related to a player
  skillbar.info.other:
    default: true
    description: permission to see info related to other player
  skillbar.*:
    default: op
    description: permission to use all command
    children:
      skillbar.reload: true
      skillbar.ban: true
      skillbar.info: true
      skillbar.info.other: true
      skillbar.forceban: true